"""empty message

Revision ID: 432be91a658d
Revises: 23aca96d34e2
Create Date: 2022-02-02 18:05:54.115283

"""

# revision identifiers, used by Alembic.
revision = '432be91a658d'
down_revision = '23aca96d34e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
